version: 2

references:
  gems_key: &gems_key
              1-gems-{{ checksum "Gemfile.lock" }}

  restore_gems_cache: &restore_gems_cache
    restore_cache:
      key: *gems_key

  install_bundler_fastlane: &install_bundle_fastlane
    run:
      name: Install Bundler & Fastlane
      command: |
        bundle check || bundle update

  save_cache_gem: &save_cache_gem
    save_cache:
      key: *gems_key
      paths:
        - vendor/bundle

  create_secret_properties: &create_secret_properties
    run:
      name: Create secret.properties
      command: sed
        -e s/CI_ENVIRONMENT/${ENVIRONMENT}/g
        secret.properties.example > secret.properties

  keep_artifacts_tests: &keep_artifacts_tests
    store_test_results:
      path: test_output/report.xml

  keep_artifacts_tests_scan: &keep_artifacts_tests_scan
    store_artifacts:
      path: /tmp/test-results
      destination: scan-test-results

  keep_artifacts_logs: &keep_artifacts_logs
    store_artifacts:
      path: ~/Library/Logs/scan
      destination: scan-logs

  test_branch: &test_branch
    run:
      name: Run tests!
      command: |
        bundle install &&
        bundle exec fastlane test_branch

  assemble_release: &assemble_release_candidate
    run:
      name: Assemble Release Candidate!
      command: |
        bundle install &&
        bundle exec fastlane assemble_release_candidate

  assemble_feature: &assemble_feature
    run:
      name: Assemble Feature!
      command: |
        bundle install &&
        bundle exec fastlane assemble_feature

  assemble-hotfix: &assemble_hotfix
    run:
      name: Assemble Hotfix!
      command: |
        bundle install &&
        bundle exec fastlane assemble_hotfix

  save_apk_release: &save_apk_release
    store_artifacts:
      path: ./app/build/outputs/apk/release/app-release-unsigned.apk
      destination: apk

jobs:
  run-tests:
    docker:
      - image: circleci/android:api-29-node
    working_directory: ~/brita-wallet
    steps:
      - checkout
      - *restore_gems_cache
      - *create_secret_properties
      - *install_bundle_fastlane
      - *save_cache_gem
      - *test_branch
      - *keep_artifacts_tests
      - *keep_artifacts_tests_scan
      - *keep_artifacts_logs

  assemble-release-candidate:
    docker:
      - image: circleci/android:api-29-node
    working_directory: ~/brita-wallet
    steps:
      - checkout
      - *restore_gems_cache
      - *create_secret_properties
      - *install_bundle_fastlane
      - *save_cache_gem
      - *assemble_release_candidate
      - *save_apk_release
      - *keep_artifacts_tests
      - *keep_artifacts_tests_scan
      - *keep_artifacts_logs

  assemble-feature:
    docker:
      - image: circleci/android:api-29-node
    working_directory: ~/brita-wallet
    steps:
      - checkout
      - *restore_gems_cache
      - *install_bundle_fastlane
      - *save_cache_gem
      - *assemble_feature

  assemble-hotfix:
    docker:
      - image: circleci/android:api-29-node
    working_directory: ~/brita-wallet
    steps:
      - checkout
      - *restore_gems_cache
      - *install_bundle_fastlane
      - *save_cache_gem
      - *assemble_hotfix

workflows:
  version: 2
  verify-branch:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - /^hotfix.*/
      - assemble-hotfix:
          requires:
            - run-tests

  deliver-feature:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - /^feature.*/
      - assemble-feature:
          requires:
            - run-tests

  deliver-release-candidate:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - develop
      - assemble-release-candidate:
          requires:
            - run-tests